//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.17 at 02:46:39 PM BRT
//


package com.hidroplan.webservice.model.gettaxon;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.base.PerfilTaxon;
import com.hidroplan.persistence.consolidation.model.base.Taxon;
import com.hidroplan.persistence.consolidation.model.base.Vernacularname;
import com.hidroplan.webservice.model.listperfiltaxon.ItemPerfilTaxon;
import com.hidroplan.webservice.model.listperfiltaxon.ListPerfilTaxon;
import com.hidroplan.webservice.model.listvernacularname.ItemVernacularName;
import com.hidroplan.webservice.model.listvernacularname.ListVernacularName;


/**
 * <p>Java class for GetTaxonResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GetTaxonResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idTaxon" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="scientificName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acceptedNameUsage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parentNameUsage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phylum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="classTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="family" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="genus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specificEpithet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="infraspecificEpithet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxonRank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scientificNameAuthorship" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxonomicStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomenclaturalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bibliographicCitation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referencesTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listPerfilTaxon" type="{http://hidroplan.com/webservice/model/listperfiltaxon}ListPerfilTaxon" minOccurs="0"/>
 *         &lt;element name="listVernacularName" type="{http://hidroplan.com/webservice/model/listvernacularname}ListVernacularName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTaxonResponse", propOrder = {
    "idTaxon",
    "scientificName",
    "acceptedNameUsage",
    "parentNameUsage",
    "phylum",
    "classTaxon",
    "orderTaxon",
    "family",
    "genus",
    "specificEpithet",
    "infraspecificEpithet",
    "taxonRank",
    "scientificNameAuthorship",
    "taxonomicStatus",
    "nomenclaturalStatus",
    "modified",
    "bibliographicCitation",
    "referencesTaxon",
    "listPerfilTaxon",
    "listVernacularName"
})
public class GetTaxonResponse {

    protected BigDecimal idTaxon;
    protected String scientificName;
    protected String acceptedNameUsage;
    protected String parentNameUsage;
    protected String phylum;
    protected String classTaxon;
    protected String orderTaxon;
    protected String family;
    protected String genus;
    protected String specificEpithet;
    protected String infraspecificEpithet;
    protected String taxonRank;
    protected String scientificNameAuthorship;
    protected String taxonomicStatus;
    protected String nomenclaturalStatus;
    protected String modified;
    protected String bibliographicCitation;
    protected String referencesTaxon;
    protected ListPerfilTaxon listPerfilTaxon;
    protected ListVernacularName listVernacularName;

    public GetTaxonResponse() {
		super();
	}

	public GetTaxonResponse(Taxon taxon) {
		this.idTaxon = new BigDecimal(taxon.getId());
		this.scientificName = taxon.getScientificName();
		this.acceptedNameUsage = taxon.getAcceptedNameUsage();
		this.parentNameUsage = taxon.getParentNameUsage();
		this.phylum = taxon.getPhylum();
		this.classTaxon = taxon.getClass_() == null ? null : taxon.getClass_().toString();
		this.orderTaxon = taxon.getOrderTaxon();
		this.family = taxon.getFamily();
		this.genus = taxon.getGenus();
		this.specificEpithet = taxon.getSpecificEpithet();
		this.infraspecificEpithet = taxon.getInfraspecificEpithet();
		this.taxonRank = getTaxonRank();
		this.scientificNameAuthorship = taxon.getScientificNameAuthorship();
		this.taxonomicStatus = taxon.getTaxonomicStatus();
		this.nomenclaturalStatus = taxon.getNomenclaturalStatus();
		this.modified = taxon.getModified();
		this.bibliographicCitation = taxon.getBibliographicCitation();
		this.referencesTaxon = taxon.getReferencesTaxon();

		this.listVernacularName = new ListVernacularName();
		for (Vernacularname vernacularName : taxon.getVernacularnames()){
			this.listVernacularName.getItensLista().add(convertToModel(vernacularName));
		}
		this.listPerfilTaxon = new ListPerfilTaxon();
		for (PerfilTaxon perfil : taxon.getPerfilTaxons()){
			this.listPerfilTaxon.getItensLista().add(convertToModel(perfil));
		}

	}



	private ItemPerfilTaxon convertToModel(PerfilTaxon perfilTaxon){
		return new ItemPerfilTaxon(perfilTaxon);
	}

	private ItemVernacularName convertToModel(Vernacularname vernacularName){
		return new ItemVernacularName(vernacularName);
	}

   /**
     * Gets the value of the idTaxon property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getIdTaxon() {
        return idTaxon;
    }

    /**
     * Sets the value of the idTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setIdTaxon(BigDecimal value) {
        this.idTaxon = value;
    }

    /**
     * Gets the value of the scientificName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getScientificName() {
        return scientificName;
    }

    /**
     * Sets the value of the scientificName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setScientificName(String value) {
        this.scientificName = value;
    }

    /**
     * Gets the value of the acceptedNameUsage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcceptedNameUsage() {
        return acceptedNameUsage;
    }

    /**
     * Sets the value of the acceptedNameUsage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcceptedNameUsage(String value) {
        this.acceptedNameUsage = value;
    }

    /**
     * Gets the value of the parentNameUsage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getParentNameUsage() {
        return parentNameUsage;
    }

    /**
     * Sets the value of the parentNameUsage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setParentNameUsage(String value) {
        this.parentNameUsage = value;
    }

    /**
     * Gets the value of the phylum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPhylum() {
        return phylum;
    }

    /**
     * Sets the value of the phylum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPhylum(String value) {
        this.phylum = value;
    }

    /**
     * Gets the value of the classTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getClassTaxon() {
        return classTaxon;
    }

    /**
     * Sets the value of the classTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setClassTaxon(String value) {
        this.classTaxon = value;
    }

    /**
     * Gets the value of the orderTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrderTaxon() {
        return orderTaxon;
    }

    /**
     * Sets the value of the orderTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrderTaxon(String value) {
        this.orderTaxon = value;
    }

    /**
     * Gets the value of the family property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the genus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGenus() {
        return genus;
    }

    /**
     * Sets the value of the genus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGenus(String value) {
        this.genus = value;
    }

    /**
     * Gets the value of the specificEpithet property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSpecificEpithet() {
        return specificEpithet;
    }

    /**
     * Sets the value of the specificEpithet property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSpecificEpithet(String value) {
        this.specificEpithet = value;
    }

    /**
     * Gets the value of the infraspecificEpithet property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInfraspecificEpithet() {
        return infraspecificEpithet;
    }

    /**
     * Sets the value of the infraspecificEpithet property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInfraspecificEpithet(String value) {
        this.infraspecificEpithet = value;
    }

    /**
     * Gets the value of the taxonRank property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTaxonRank() {
        return taxonRank;
    }

    /**
     * Sets the value of the taxonRank property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTaxonRank(String value) {
        this.taxonRank = value;
    }

    /**
     * Gets the value of the scientificNameAuthorship property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getScientificNameAuthorship() {
        return scientificNameAuthorship;
    }

    /**
     * Sets the value of the scientificNameAuthorship property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setScientificNameAuthorship(String value) {
        this.scientificNameAuthorship = value;
    }

    /**
     * Gets the value of the taxonomicStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTaxonomicStatus() {
        return taxonomicStatus;
    }

    /**
     * Sets the value of the taxonomicStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTaxonomicStatus(String value) {
        this.taxonomicStatus = value;
    }

    /**
     * Gets the value of the nomenclaturalStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenclaturalStatus() {
        return nomenclaturalStatus;
    }

    /**
     * Sets the value of the nomenclaturalStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenclaturalStatus(String value) {
        this.nomenclaturalStatus = value;
    }

    /**
     * Gets the value of the modified property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setModified(String value) {
        this.modified = value;
    }

    /**
     * Gets the value of the bibliographicCitation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBibliographicCitation() {
        return bibliographicCitation;
    }

    /**
     * Sets the value of the bibliographicCitation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBibliographicCitation(String value) {
        this.bibliographicCitation = value;
    }

    /**
     * Gets the value of the referencesTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReferencesTaxon() {
        return referencesTaxon;
    }

    /**
     * Sets the value of the referencesTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReferencesTaxon(String value) {
        this.referencesTaxon = value;
    }

    /**
     * Gets the value of the listPerfilTaxon property.
     *
     * @return
     *     possible object is
     *     {@link ListPerfilTaxon }
     *
     */
    public ListPerfilTaxon getListPerfilTaxon() {
        return listPerfilTaxon;
    }

    /**
     * Sets the value of the listPerfilTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link ListPerfilTaxon }
     *
     */
    public void setListPerfilTaxon(ListPerfilTaxon value) {
        this.listPerfilTaxon = value;
    }

    /**
     * Gets the value of the listVernacularName property.
     *
     * @return
     *     possible object is
     *     {@link ListVernacularName }
     *
     */
    public ListVernacularName getListVernacularName() {
        return listVernacularName;
    }

    /**
     * Sets the value of the listVernacularName property.
     *
     * @param value
     *     allowed object is
     *     {@link ListVernacularName }
     *
     */
    public void setListVernacularName(ListVernacularName value) {
        this.listVernacularName = value;
    }

}
