//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.17 at 07:40:04 PM BRT
//


package com.hidroplan.webservice.model.listvernacularname;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.base.Vernacularname;


/**
 * <p>Java class for ItemVernacularName complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ItemVernacularName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idVernacularName" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="vernacularName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemVernacularName", propOrder = {
    "idVernacularName",
    "vernacularName",
    "language",
    "locality"
})
public class ItemVernacularName {

    protected BigDecimal idVernacularName;
    @XmlElement(required = true)
    protected String vernacularName;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String locality;



    public ItemVernacularName() {
		super();
	}



	public ItemVernacularName(Vernacularname vernacularName) {
		super();
		this.idVernacularName = new BigDecimal(vernacularName.getId().getId());
		this.vernacularName = vernacularName.getId().getVernacularName();
		this.language = vernacularName.getId().getLanguage();
		this.locality = vernacularName.getId().getLocality();
	}



	/**
     * Gets the value of the idVernacularName property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getIdVernacularName() {
        return idVernacularName;
    }

    /**
     * Sets the value of the idVernacularName property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setIdVernacularName(BigDecimal value) {
        this.idVernacularName = value;
    }

    /**
     * Gets the value of the vernacularName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVernacularName() {
        return vernacularName;
    }

    /**
     * Sets the value of the vernacularName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVernacularName(String value) {
        this.vernacularName = value;
    }

    /**
     * Gets the value of the language property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the locality property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLocality(String value) {
        this.locality = value;
    }

}
