//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.17 at 04:32:29 PM BRT
//


package com.hidroplan.webservice.model.listcondicoesambientais;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.typing.TypeFatorAmbiente;
import com.hidroplan.persistence.consolidation.model.typing.TypeStatusArduino;


/**
 * <p>Java class for ItemCondicaoAmbiental complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ItemCondicaoAmbiental">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fatorAmbiental" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grandeza" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unidadeDeMedida" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusArduino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemCondicaoAmbiental", propOrder = {
    "fatorAmbiental",
    "grandeza",
    "unidadeDeMedida",
    "statusArduino"
})
public class ItemCondicaoAmbiental {

    @XmlElement(required = true)
    protected TypeFatorAmbiente fatorAmbiental;
    @XmlElement(required = true)
    protected BigDecimal grandeza;
    @XmlElement(required = true)
    protected String unidadeDeMedida;
    protected TypeStatusArduino statusArduino;

    /**
     * Gets the value of the fatorAmbiental property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypeFatorAmbiente getFatorAmbiental() {
        return fatorAmbiental;
    }

    /**
     * Sets the value of the fatorAmbiental property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFatorAmbiental(TypeFatorAmbiente value) {
        this.fatorAmbiental = value;
    }

    /**
     * Gets the value of the grandeza property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getGrandeza() {
        return grandeza;
    }

    /**
     * Sets the value of the grandeza property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setGrandeza(BigDecimal value) {
        this.grandeza = value;
    }

    /**
     * Gets the value of the unidadeDeMedida property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUnidadeDeMedida() {
        return unidadeDeMedida;
    }

    /**
     * Sets the value of the unidadeDeMedida property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUnidadeDeMedida(String value) {
        this.unidadeDeMedida = value;
    }

    /**
     * Gets the value of the statusArduino property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypeStatusArduino getStatusArduino() {
        return statusArduino;
    }

    /**
     * Sets the value of the statusArduino property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatusArduino(TypeStatusArduino value) {
        this.statusArduino = value;
    }

}
