//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.17 at 10:07:57 PM BRT
//


package com.hidroplan.webservice.model.listsolucaonutritiva;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.typing.TypeStatusArduino;


/**
 * <p>Java class for ItemElemento complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ItemElemento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idElemento" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="nameElemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="molPerL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="symbolElemento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="atomicNumberElemento" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="atomicWeightElemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="densityElemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eletronicConfigurationtElemento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusArduino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemElemento", propOrder = {
    "idElemento",
    "nameElemento",
    "molPerL",
    "symbolElemento",
    "atomicNumberElemento",
    "atomicWeightElemento",
    "densityElemento",
    "eletronicConfigurationtElemento",
    "statusArduino"
})
public class ItemElemento {

    protected BigDecimal idElemento;
    protected String nameElemento;
    @XmlElement(required = true)
    protected String molPerL;
    @XmlElement(required = true)
    protected String symbolElemento;
    protected BigDecimal atomicNumberElemento;
    protected String atomicWeightElemento;
    protected String densityElemento;
    protected String eletronicConfigurationtElemento;
    protected TypeStatusArduino statusArduino;

    /**
     * Gets the value of the idElemento property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getIdElemento() {
        return idElemento;
    }

    /**
     * Sets the value of the idElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setIdElemento(BigDecimal value) {
        this.idElemento = value;
    }

    /**
     * Gets the value of the nameElemento property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameElemento() {
        return nameElemento;
    }

    /**
     * Sets the value of the nameElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameElemento(String value) {
        this.nameElemento = value;
    }

    /**
     * Gets the value of the molPerL property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMolPerL() {
        return molPerL;
    }

    /**
     * Sets the value of the molPerL property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMolPerL(String value) {
        this.molPerL = value;
    }

    /**
     * Gets the value of the symbolElemento property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSymbolElemento() {
        return symbolElemento;
    }

    /**
     * Sets the value of the symbolElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSymbolElemento(String value) {
        this.symbolElemento = value;
    }

    /**
     * Gets the value of the atomicNumberElemento property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getAtomicNumberElemento() {
        return atomicNumberElemento;
    }

    /**
     * Sets the value of the atomicNumberElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setAtomicNumberElemento(BigDecimal value) {
        this.atomicNumberElemento = value;
    }

    /**
     * Gets the value of the atomicWeightElemento property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAtomicWeightElemento() {
        return atomicWeightElemento;
    }

    /**
     * Sets the value of the atomicWeightElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAtomicWeightElemento(String value) {
        this.atomicWeightElemento = value;
    }

    /**
     * Gets the value of the densityElemento property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDensityElemento() {
        return densityElemento;
    }

    /**
     * Sets the value of the densityElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDensityElemento(String value) {
        this.densityElemento = value;
    }

    /**
     * Gets the value of the eletronicConfigurationtElemento property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEletronicConfigurationtElemento() {
        return eletronicConfigurationtElemento;
    }

    /**
     * Sets the value of the eletronicConfigurationtElemento property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEletronicConfigurationtElemento(String value) {
        this.eletronicConfigurationtElemento = value;
    }

        /**
     * Gets the value of the statusArduino property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypeStatusArduino getStatusArduino() {
        return statusArduino;
    }

    /**
     * Sets the value of the statusArduino property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatusArduino(TypeStatusArduino value) {
        this.statusArduino = value;
    }

}
