//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.17 at 09:36:29 PM BRT
//


package com.hidroplan.webservice.model.getenvironment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.typing.TypePerfilTaxon;
import com.hidroplan.webservice.model.listcondicoesambientais.ListCondicoesAmbientais;
import com.hidroplan.webservice.model.listsolucaonutritiva.ListSolucaoNutritiva;


/**
 * <p>Java class for GetEnvironmentRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GetEnvironmentRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idArduino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listCondicoesAmbientais" type="{http://hidroplan.com/webservice/model/listcondicoesambientais}ListCondicoesAmbientais" minOccurs="0"/>
 *         &lt;element name="listSolucaoNutritiva" type="{http://hidroplan.com/webservice/model/listsolucaonutritiva}ListSolucaoNutritiva" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetEnvironmentRequest", propOrder = {
    "idArduino",
    "idTaxon",
    "tipo",
    "listCondicoesAmbientais",
    "listSolucaoNutritiva"
})
public class GetEnvironmentRequest {

    protected String idArduino;
    protected String idTaxon;
    protected TypePerfilTaxon tipo;
    protected ListCondicoesAmbientais listCondicoesAmbientais;
    protected ListSolucaoNutritiva listSolucaoNutritiva;

   /**
     * Gets the value of the idArduino property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdArduino() {
        return idArduino;
    }

    /**
     * Sets the value of the idArduino property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdArduino(String value) {
        this.idArduino = value;
    }

    /**
     * Gets the value of the idTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdTaxon() {
        return idTaxon;
    }

    /**
     * Sets the value of the idTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdTaxon(String value) {
        this.idTaxon = value;
    }

    /**
     * Gets the value of the tipo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypePerfilTaxon getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipo(TypePerfilTaxon value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the listCondicoesAmbientais property.
     *
     * @return
     *     possible object is
     *     {@link ListCondicoesAmbientais }
     *
     */
    public ListCondicoesAmbientais getListCondicoesAmbientais() {
        return listCondicoesAmbientais;
    }

    /**
     * Sets the value of the listCondicoesAmbientais property.
     *
     * @param value
     *     allowed object is
     *     {@link ListCondicoesAmbientais }
     *
     */
    public void setListCondicoesAmbientais(ListCondicoesAmbientais value) {
        this.listCondicoesAmbientais = value;
    }

    /**
     * Gets the value of the listSolucaoNutritiva property.
     *
     * @return
     *     possible object is
     *     {@link ListSolucaoNutritiva }
     *
     */
    public ListSolucaoNutritiva getListSolucaoNutritiva() {
        return listSolucaoNutritiva;
    }

    /**
     * Sets the value of the listSolucaoNutritiva property.
     *
     * @param value
     *     allowed object is
     *     {@link ListSolucaoNutritiva }
     *
     */
    public void setListSolucaoNutritiva(ListSolucaoNutritiva value) {
        this.listSolucaoNutritiva = value;
    }

}
