//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.18 at 04:06:10 PM BRT
//


package com.hidroplan.webservice.model.createsolucaonutritiva;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.typing.TypePerfilTaxon;
import com.hidroplan.webservice.model.listsolucaonutritiva.ListSolucaoNutritiva;


/**
 * <p>Java class for CreateSolucaoNutritivaRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateSolucaoNutritivaRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoTaxonPerfil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listSolucaoNutritiva" type="{http://hidroplan.com/webservice/model/listsolucaonutritiva}ListSolucaoNutritiva" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateSolucaoNutritivaRequest", propOrder = {
    "idTaxon",
    "tipoTaxonPerfil",
    "listSolucaoNutritiva"
})
public class CreateSolucaoNutritivaRequest {

    protected String idTaxon;
    protected TypePerfilTaxon tipoTaxonPerfil;
    protected ListSolucaoNutritiva listSolucaoNutritiva;

    /**
     * Gets the value of the idTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdTaxon() {
        return idTaxon;
    }

    /**
     * Sets the value of the idTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdTaxon(String value) {
        this.idTaxon = value;
    }

    /**
     * Gets the value of the tipoTaxonPerfil property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypePerfilTaxon getTipoTaxonPerfil() {
        return tipoTaxonPerfil;
    }

    /**
     * Sets the value of the tipoTaxonPerfil property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoTaxonPerfil(TypePerfilTaxon value) {
        this.tipoTaxonPerfil = value;
    }

    /**
     * Gets the value of the listSolucaoNutritiva property.
     *
     * @return
     *     possible object is
     *     {@link ListSolucaoNutritiva }
     *
     */
    public ListSolucaoNutritiva getListSolucaoNutritiva() {
        return listSolucaoNutritiva;
    }

    /**
     * Sets the value of the listSolucaoNutritiva property.
     *
     * @param value
     *     allowed object is
     *     {@link ListSolucaoNutritiva }
     *
     */
    public void setListSolucaoNutritiva(ListSolucaoNutritiva value) {
        this.listSolucaoNutritiva = value;
    }

}
