//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.18 at 04:06:10 PM BRT 
//


package com.hidroplan.webservice.model.createsolucaonutritiva;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hidroplan.webservice.model.createsolucaonutritiva package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateSolucaNutritivaRequest_QNAME = new QName("http://hidroplan.com/webservice/model/createsolucaonutritiva", "createSolucaNutritivaRequest");
    private final static QName _CreateSolucaNutritivaResponse_QNAME = new QName("http://hidroplan.com/webservice/model/createsolucaonutritiva", "createSolucaNutritivaResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hidroplan.webservice.model.createsolucaonutritiva
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateSolucaoNutritivaRequest }
     * 
     */
    public CreateSolucaoNutritivaRequest createCreateSolucaoNutritivaRequest() {
        return new CreateSolucaoNutritivaRequest();
    }

    /**
     * Create an instance of {@link CreateSolucaoNutritivaResponse }
     * 
     */
    public CreateSolucaoNutritivaResponse createCreateSolucaoNutritivaResponse() {
        return new CreateSolucaoNutritivaResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSolucaoNutritivaRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hidroplan.com/webservice/model/createsolucaonutritiva", name = "createSolucaNutritivaRequest")
    public JAXBElement<CreateSolucaoNutritivaRequest> createCreateSolucaNutritivaRequest(CreateSolucaoNutritivaRequest value) {
        return new JAXBElement<CreateSolucaoNutritivaRequest>(_CreateSolucaNutritivaRequest_QNAME, CreateSolucaoNutritivaRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateSolucaoNutritivaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hidroplan.com/webservice/model/createsolucaonutritiva", name = "createSolucaNutritivaResponse")
    public JAXBElement<CreateSolucaoNutritivaResponse> createCreateSolucaNutritivaResponse(CreateSolucaoNutritivaResponse value) {
        return new JAXBElement<CreateSolucaoNutritivaResponse>(_CreateSolucaNutritivaResponse_QNAME, CreateSolucaoNutritivaResponse.class, null, value);
    }

}
