//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.18 at 02:50:23 PM BRT
//


package com.hidroplan.webservice.model.createfatorambiente;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.hidroplan.persistence.consolidation.model.typing.TypeFatorAmbiente;
import com.hidroplan.persistence.consolidation.model.typing.TypePerfilTaxon;


/**
 * <p>Java class for CreateFatorAmbienteRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateFatorAmbienteRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idTaxon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoTaxonPerfil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="valorFatorAmbiente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unidadeDoValorFatorAmbiente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoFatorAmbiente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateFatorAmbienteRequest", propOrder = {
    "idTaxon",
    "tipoTaxonPerfil",
    "valorFatorAmbiente",
    "unidadeDoValorFatorAmbiente",
    "tipoFatorAmbiente"
})
public class CreateFatorAmbienteRequest {

    protected String idTaxon;
    protected TypePerfilTaxon tipoTaxonPerfil;
    protected String valorFatorAmbiente;
    protected String unidadeDoValorFatorAmbiente;
    protected TypeFatorAmbiente tipoFatorAmbiente;

    /**
     * Gets the value of the idTaxon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIdTaxon() {
        return idTaxon;
    }

    /**
     * Sets the value of the idTaxon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIdTaxon(String value) {
        this.idTaxon = value;
    }

    /**
     * Gets the value of the tipoTaxonPerfil property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypePerfilTaxon getTipoTaxonPerfil() {
        return tipoTaxonPerfil;
    }

    /**
     * Sets the value of the tipoTaxonPerfil property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoTaxonPerfil(TypePerfilTaxon value) {
        this.tipoTaxonPerfil = value;
    }

    /**
     * Gets the value of the valorFatorAmbiente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValorFatorAmbiente() {
        return valorFatorAmbiente;
    }

    /**
     * Sets the value of the valorFatorAmbiente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValorFatorAmbiente(String value) {
        this.valorFatorAmbiente = value;
    }

    /**
     * Gets the value of the unidadeDoValorFatorAmbiente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUnidadeDoValorFatorAmbiente() {
        return unidadeDoValorFatorAmbiente;
    }

    /**
     * Sets the value of the unidadeDoValorFatorAmbiente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUnidadeDoValorFatorAmbiente(String value) {
        this.unidadeDoValorFatorAmbiente = value;
    }

    /**
     * Gets the value of the tipoFatorAmbiente property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public TypeFatorAmbiente getTipoFatorAmbiente() {
        return tipoFatorAmbiente;
    }

    /**
     * Sets the value of the tipoFatorAmbiente property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipoFatorAmbiente(TypeFatorAmbiente value) {
        this.tipoFatorAmbiente = value;
    }

}
