//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.18 at 02:50:23 PM BRT 
//


package com.hidroplan.webservice.model.createfatorambiente;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hidroplan.webservice.model.createfatorambiente package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateFatorAmbienteResponse_QNAME = new QName("http://hidroplan.com/webservice/model/createfatorambiente", "createFatorAmbienteResponse");
    private final static QName _CreateFatorAmbienteRequest_QNAME = new QName("http://hidroplan.com/webservice/model/createfatorambiente", "createFatorAmbienteRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hidroplan.webservice.model.createfatorambiente
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateFatorAmbienteRequest }
     * 
     */
    public CreateFatorAmbienteRequest createCreateFatorAmbienteRequest() {
        return new CreateFatorAmbienteRequest();
    }

    /**
     * Create an instance of {@link CreateFatorAmbienteResponse }
     * 
     */
    public CreateFatorAmbienteResponse createCreateFatorAmbienteResponse() {
        return new CreateFatorAmbienteResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateFatorAmbienteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hidroplan.com/webservice/model/createfatorambiente", name = "createFatorAmbienteResponse")
    public JAXBElement<CreateFatorAmbienteResponse> createCreateFatorAmbienteResponse(CreateFatorAmbienteResponse value) {
        return new JAXBElement<CreateFatorAmbienteResponse>(_CreateFatorAmbienteResponse_QNAME, CreateFatorAmbienteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateFatorAmbienteRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hidroplan.com/webservice/model/createfatorambiente", name = "createFatorAmbienteRequest")
    public JAXBElement<CreateFatorAmbienteRequest> createCreateFatorAmbienteRequest(CreateFatorAmbienteRequest value) {
        return new JAXBElement<CreateFatorAmbienteRequest>(_CreateFatorAmbienteRequest_QNAME, CreateFatorAmbienteRequest.class, null, value);
    }

}
