package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Elementos generated by hbm2java
 */
@Entity
@Table(name = "elementos", catalog = "hidroplan")
public class Elementos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 412912227923847055L;
	private int id;
	private String name;
	private String symbol;
	private Integer atomicNumber;
	private String atomicWeight;
	private String density;
	private String meltingPoint;
	private String boilingPoint;
	private String atomicRadius;
	private String covalentRadius;
	private Integer ionicRadius;
	private String specificVolume;
	private String specificHeat;
	private String heatFusion;
	private String heatEvaporation;
	private String thermalConductivity;
	private String paulingElectronegativity;
	private String firstIonisationEnergy;
	private String oxidationStates;
	private String electronicConfiguration;
	private String lattice;
	private String latticeConstant;
	private Set<SolucaoNutritivaElemento> solucaoNutritivaElementos = new HashSet<SolucaoNutritivaElemento>(0);

	public Elementos() {
	}

	public Elementos(int id) {
		this.id = id;
	}

	public Elementos(int id, String name, String symbol, Integer atomicNumber, String atomicWeight, String density,
			String meltingPoint, String boilingPoint, String atomicRadius, String covalentRadius, Integer ionicRadius,
			String specificVolume, String specificHeat, String heatFusion, String heatEvaporation,
			String thermalConductivity, String paulingElectronegativity, String firstIonisationEnergy,
			String oxidationStates, String electronicConfiguration, String lattice, String latticeConstant,
			Set<SolucaoNutritivaElemento> solucaoNutritivaElementos) {
		this.id = id;
		this.name = name;
		this.symbol = symbol;
		this.atomicNumber = atomicNumber;
		this.atomicWeight = atomicWeight;
		this.density = density;
		this.meltingPoint = meltingPoint;
		this.boilingPoint = boilingPoint;
		this.atomicRadius = atomicRadius;
		this.covalentRadius = covalentRadius;
		this.ionicRadius = ionicRadius;
		this.specificVolume = specificVolume;
		this.specificHeat = specificHeat;
		this.heatFusion = heatFusion;
		this.heatEvaporation = heatEvaporation;
		this.thermalConductivity = thermalConductivity;
		this.paulingElectronegativity = paulingElectronegativity;
		this.firstIonisationEnergy = firstIonisationEnergy;
		this.oxidationStates = oxidationStates;
		this.electronicConfiguration = electronicConfiguration;
		this.lattice = lattice;
		this.latticeConstant = latticeConstant;
		this.solucaoNutritivaElementos = solucaoNutritivaElementos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 12)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "symbol", length = 3)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Column(name = "atomic_number")
	public Integer getAtomicNumber() {
		return this.atomicNumber;
	}

	public void setAtomicNumber(Integer atomicNumber) {
		this.atomicNumber = atomicNumber;
	}

	@Column(name = "atomic_weight", length = 9)
	public String getAtomicWeight() {
		return this.atomicWeight;
	}

	public void setAtomicWeight(String atomicWeight) {
		this.atomicWeight = atomicWeight;
	}

	@Column(name = "density", length = 23)
	public String getDensity() {
		return this.density;
	}

	public void setDensity(String density) {
		this.density = density;
	}

	@Column(name = "melting_point", length = 7)
	public String getMeltingPoint() {
		return this.meltingPoint;
	}

	public void setMeltingPoint(String meltingPoint) {
		this.meltingPoint = meltingPoint;
	}

	@Column(name = "boiling_point", length = 7)
	public String getBoilingPoint() {
		return this.boilingPoint;
	}

	public void setBoilingPoint(String boilingPoint) {
		this.boilingPoint = boilingPoint;
	}

	@Column(name = "atomic_radius", length = 3)
	public String getAtomicRadius() {
		return this.atomicRadius;
	}

	public void setAtomicRadius(String atomicRadius) {
		this.atomicRadius = atomicRadius;
	}

	@Column(name = "covalent_radius", length = 5)
	public String getCovalentRadius() {
		return this.covalentRadius;
	}

	public void setCovalentRadius(String covalentRadius) {
		this.covalentRadius = covalentRadius;
	}

	@Column(name = "ionic_radius")
	public Integer getIonicRadius() {
		return this.ionicRadius;
	}

	public void setIonicRadius(Integer ionicRadius) {
		this.ionicRadius = ionicRadius;
	}

	@Column(name = "specific_volume", length = 5)
	public String getSpecificVolume() {
		return this.specificVolume;
	}

	public void setSpecificVolume(String specificVolume) {
		this.specificVolume = specificVolume;
	}

	@Column(name = "specific_heat", length = 13)
	public String getSpecificHeat() {
		return this.specificHeat;
	}

	public void setSpecificHeat(String specificHeat) {
		this.specificHeat = specificHeat;
	}

	@Column(name = "heat_fusion", length = 13)
	public String getHeatFusion() {
		return this.heatFusion;
	}

	public void setHeatFusion(String heatFusion) {
		this.heatFusion = heatFusion;
	}

	@Column(name = "heat_evaporation", length = 13)
	public String getHeatEvaporation() {
		return this.heatEvaporation;
	}

	public void setHeatEvaporation(String heatEvaporation) {
		this.heatEvaporation = heatEvaporation;
	}

	@Column(name = "thermal_conductivity", length = 8)
	public String getThermalConductivity() {
		return this.thermalConductivity;
	}

	public void setThermalConductivity(String thermalConductivity) {
		this.thermalConductivity = thermalConductivity;
	}

	@Column(name = "pauling_electronegativity", length = 4)
	public String getPaulingElectronegativity() {
		return this.paulingElectronegativity;
	}

	public void setPaulingElectronegativity(String paulingElectronegativity) {
		this.paulingElectronegativity = paulingElectronegativity;
	}

	@Column(name = "first_ionisation_energy", length = 6)
	public String getFirstIonisationEnergy() {
		return this.firstIonisationEnergy;
	}

	public void setFirstIonisationEnergy(String firstIonisationEnergy) {
		this.firstIonisationEnergy = firstIonisationEnergy;
	}

	@Column(name = "oxidation_states", length = 14)
	public String getOxidationStates() {
		return this.oxidationStates;
	}

	public void setOxidationStates(String oxidationStates) {
		this.oxidationStates = oxidationStates;
	}

	@Column(name = "electronic_configuration", length = 20)
	public String getElectronicConfiguration() {
		return this.electronicConfiguration;
	}

	public void setElectronicConfiguration(String electronicConfiguration) {
		this.electronicConfiguration = electronicConfiguration;
	}

	@Column(name = "lattice", length = 3)
	public String getLattice() {
		return this.lattice;
	}

	public void setLattice(String lattice) {
		this.lattice = lattice;
	}

	@Column(name = "lattice_constant", length = 5)
	public String getLatticeConstant() {
		return this.latticeConstant;
	}

	public void setLatticeConstant(String latticeConstant) {
		this.latticeConstant = latticeConstant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elementos")
	public Set<SolucaoNutritivaElemento> getSolucaoNutritivaElementos() {
		return this.solucaoNutritivaElementos;
	}

	public void setSolucaoNutritivaElementos(Set<SolucaoNutritivaElemento> solucaoNutritivaElementos) {
		this.solucaoNutritivaElementos = solucaoNutritivaElementos;
	}

}
