package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.hidroplan.persistence.consolidation.model.typing.TypeFatorAmbiente;

/**
 * FatorAmbiente generated by hbm2java
 */
@Entity
@Table(name = "fator_ambiente", catalog = "hidroplan", uniqueConstraints = @UniqueConstraint(columnNames = "id_perfil_taxon"))
public class FatorAmbiente implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 309912711161791988L;
	private int id;
	private PerfilTaxon perfilTaxon;
	private BigDecimal valor;
	private String unidadeGrandeza;
	private TypeFatorAmbiente tipo;

	public FatorAmbiente() {
	}

	public FatorAmbiente(int id, PerfilTaxon perfilTaxon) {
		this.id = id;
		this.perfilTaxon = perfilTaxon;
	}

	public FatorAmbiente(int id, PerfilTaxon perfilTaxon, BigDecimal valor, String unidadeGrandeza, TypeFatorAmbiente tipo) {
		this.id = id;
		this.perfilTaxon = perfilTaxon;
		this.valor = valor;
		this.unidadeGrandeza = unidadeGrandeza;
		this.tipo = tipo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil_taxon", unique = true, nullable = false)
	public PerfilTaxon getPerfilTaxon() {
		return this.perfilTaxon;
	}

	public void setPerfilTaxon(PerfilTaxon perfilTaxon) {
		this.perfilTaxon = perfilTaxon;
	}

	@Column(name = "valor", scale = 4)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "unidade_grandeza", length = 10)
	public String getUnidadeGrandeza() {
		return this.unidadeGrandeza;
	}

	public void setUnidadeGrandeza(String unidadeGrandeza) {
		this.unidadeGrandeza = unidadeGrandeza;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "tipo")
	public TypeFatorAmbiente getTipo() {
		return this.tipo;
	}

	public void setTipo(TypeFatorAmbiente tipo) {
		this.tipo = tipo;
	}

}
