package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SolucaoNutritivaElemento generated by hbm2java
 */
@Entity
@Table(name = "solucao_nutritiva_elemento", catalog = "hidroplan", uniqueConstraints = {
		@UniqueConstraint(columnNames = "id_elementos"), @UniqueConstraint(columnNames = "id_perfil_taxon") })
public class SolucaoNutritivaElemento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8177093714415583319L;
	private SolucaoNutritivaElementoId id;
	private Elementos elementos;
	private PerfilTaxon perfilTaxon;

	public SolucaoNutritivaElemento() {
	}

	public SolucaoNutritivaElemento(SolucaoNutritivaElementoId id, Elementos elementos, PerfilTaxon perfilTaxon) {
		this.id = id;
		this.elementos = elementos;
		this.perfilTaxon = perfilTaxon;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPerfilTaxon", column = @Column(name = "id_perfil_taxon", unique = true, nullable = false)),
			@AttributeOverride(name = "idElementos", column = @Column(name = "id_elementos", unique = true, nullable = false)),
			@AttributeOverride(name = "quantidadeElemento", column = @Column(name = "quantidade_elemento", scale = 4)) })
	public SolucaoNutritivaElementoId getId() {
		return this.id;
	}

	public void setId(SolucaoNutritivaElementoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_elementos", unique = true, nullable = false, insertable = false, updatable = false)
	public Elementos getElementos() {
		return this.elementos;
	}

	public void setElementos(Elementos elementos) {
		this.elementos = elementos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil_taxon", unique = true, nullable = false, insertable = false, updatable = false)
	public PerfilTaxon getPerfilTaxon() {
		return this.perfilTaxon;
	}

	public void setPerfilTaxon(PerfilTaxon perfilTaxon) {
		this.perfilTaxon = perfilTaxon;
	}

}
