package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolucaoNutritivaElementoId generated by hbm2java
 */
@Embeddable
public class SolucaoNutritivaElementoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7440880737541519836L;
	private int idPerfilTaxon;
	private int idElementos;
	private BigDecimal quantidadeElemento;

	public SolucaoNutritivaElementoId() {
	}

	public SolucaoNutritivaElementoId(int idPerfilTaxon, int idElementos) {
		this.idPerfilTaxon = idPerfilTaxon;
		this.idElementos = idElementos;
	}

	public SolucaoNutritivaElementoId(int idPerfilTaxon, int idElementos, BigDecimal quantidadeElemento) {
		this.idPerfilTaxon = idPerfilTaxon;
		this.idElementos = idElementos;
		this.quantidadeElemento = quantidadeElemento;
	}

	@Column(name = "id_perfil_taxon", unique = true, nullable = false)
	public int getIdPerfilTaxon() {
		return this.idPerfilTaxon;
	}

	public void setIdPerfilTaxon(int idPerfilTaxon) {
		this.idPerfilTaxon = idPerfilTaxon;
	}

	@Column(name = "id_elementos", unique = true, nullable = false)
	public int getIdElementos() {
		return this.idElementos;
	}

	public void setIdElementos(int idElementos) {
		this.idElementos = idElementos;
	}

	@Column(name = "quantidade_elemento", scale = 4)
	public BigDecimal getQuantidadeElemento() {
		return this.quantidadeElemento;
	}

	public void setQuantidadeElemento(BigDecimal quantidadeElemento) {
		this.quantidadeElemento = quantidadeElemento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SolucaoNutritivaElementoId))
			return false;
		SolucaoNutritivaElementoId castOther = (SolucaoNutritivaElementoId) other;

		return (this.getIdPerfilTaxon() == castOther.getIdPerfilTaxon())
				&& (this.getIdElementos() == castOther.getIdElementos())
				&& ((this.getQuantidadeElemento() == castOther.getQuantidadeElemento())
						|| (this.getQuantidadeElemento() != null && castOther.getQuantidadeElemento() != null
								&& this.getQuantidadeElemento().equals(castOther.getQuantidadeElemento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfilTaxon();
		result = 37 * result + this.getIdElementos();
		result = 37 * result + (getQuantidadeElemento() == null ? 0 : this.getQuantidadeElemento().hashCode());
		return result;
	}

}
