package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vernacularname generated by hbm2java
 */
@Entity
@Table(name = "vernacularname", catalog = "hidroplan")
public class Vernacularname implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2253844718083673264L;
	private VernacularnameId id;
	private Taxon taxon;

	public Vernacularname() {
	}

	public Vernacularname(VernacularnameId id, Taxon taxon) {
		this.id = id;
		this.taxon = taxon;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "vernacularName", column = @Column(name = "vernacularName")),
			@AttributeOverride(name = "language", column = @Column(name = "language")),
			@AttributeOverride(name = "locality", column = @Column(name = "locality")) })
	public VernacularnameId getId() {
		return this.id;
	}

	public void setId(VernacularnameId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	public Taxon getTaxon() {
		return this.taxon;
	}

	public void setTaxon(Taxon taxon) {
		this.taxon = taxon;
	}

}
