package com.hidroplan.persistence.consolidation.model.base;
// Generated 16/06/2017 21:45:16 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VernacularnameId generated by hbm2java
 */
@Embeddable
public class VernacularnameId implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1923478243373924841L;
	private int id;
	private String vernacularName;
	private String language;
	private String locality;

	public VernacularnameId() {
	}

	public VernacularnameId(int id) {
		this.id = id;
	}

	public VernacularnameId(int id, String vernacularName, String language, String locality) {
		this.id = id;
		this.vernacularName = vernacularName;
		this.language = language;
		this.locality = locality;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "vernacularName")
	public String getVernacularName() {
		return this.vernacularName;
	}

	public void setVernacularName(String vernacularName) {
		this.vernacularName = vernacularName;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VernacularnameId))
			return false;
		VernacularnameId castOther = (VernacularnameId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getVernacularName() == castOther.getVernacularName())
						|| (this.getVernacularName() != null && castOther.getVernacularName() != null
								&& this.getVernacularName().equals(castOther.getVernacularName())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
						&& castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getLocality() == castOther.getLocality()) || (this.getLocality() != null
						&& castOther.getLocality() != null && this.getLocality().equals(castOther.getLocality())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getVernacularName() == null ? 0 : this.getVernacularName().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result + (getLocality() == null ? 0 : this.getLocality().hashCode());
		return result;
	}

}
